name: Build and Deploy App

on:
  push:
    paths:
      - 'app/simple-api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-api:latest ./app/simple-api
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-api:latest
